sudo: false

language: php

php:
    - 7.1
    - 7.2
    - nightly

cache:
    directories:
        - $HOME/.composer/cache/files

matrix:
    fast_finish: true

    allow_failures:
        - php: nightly

before_install:
    - composer self-update

install:
    - composer update ${COMPOSER_FLAGS} --prefer-source

script:
    - vendor/bin/phpunit --colors
